import type { Metadata } from 'next';
import { Inter, Artifika } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });
const artifika = Artifika({
	subsets: ['latin'],
	weight: '400',
	variable: '--logo',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='scroll-smooth'>
			<body
				className={cn(artifika.variable, inter.className, 'bg-background ')}
			>
				{children}
			</body>
		</html>
	);
}
